### ISSUE TITLE
[Bug] NPE when enable batch push

### ISSUE THREAD

**Issue by cserwen** [openmessaging/dledger#134]
### Question
- When set `enableBatchPush` as true，It will occasionally has NPE bugs when elections occur.
```
2022-04-27 18:58:41 ERROR NettyServerPublicExecutor_1 - process request exception 
java.lang.NullPointerException: null 
       at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryHandler.buildResponse(DLedgerEntryPusher.java:808) 
       at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryHandler.handlePush(DLedgerEntryPusher.java:781) 
       at io.openmessaging.storage.dledger.DLedgerEntryPusher.handlePush(DLedgerEntryPusher.java:100) 
       at io.openmessaging.storage.dledger.DLedgerServer.handlePush(DLedgerServer.java:268) 
       at io.openmessaging.storage.dledger.DLedgerRpcNettyService.handlePush(DLedgerRpcNettyService.java:442) 
       at io.openmessaging.storage.dledger.DLedgerRpcNettyService.processRequest(DLedgerRpcNettyService.java:363) 
       at io.openmessaging.storage.dledger.DLedgerRpcNettyService$4.processRequest(DLedgerRpcNettyService.java:104) 
       at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$1.run(NettyRemotingAbstract.java:234) 
       at org.apache.rocketmq.remoting.netty.RequestTask.run(RequestTask.java:80) 
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
       at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
       at java.lang.Thread.run(Thread.java:748) 
2022-04-27 18:58:41 ERROR NettyServerPublicExecutor_1 - RemotingCommand [code=51004, language=JAVA, version=373, opaque=1357831504, flag(B)=0, remark=null, extFields=null, serializeTypeCurrentRPC=JSON]
```
### How to fix ?
https://github.com/openmessaging/dledger/blob/ac3f8016d50e182bdffa1022205120a2f1f2eee3/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java#L781
![image](https://user-images.githubusercontent.com/46882838/165668574-9911d2db-e3b9-4500-b639-c8e1c35145cb.png)

In this case, batch is not processed.

**Comment by Git-Yang** [comment]
@cserwen Refer to #137
